### ISSUE TITLE
About the code in Model.py

### ISSUE THREAD

**Issue by FayeXXX** [seq-to-mind/semi-style-transfer#2]
I'm interested in your work and when I run the code, an error occured:

Traceback (most recent call last):
  File "/home/usr/pycharm-community-2022.1/plugins/python-ce/helpers/pydev/pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/usr/pycharm-community-2022.1/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/usr/PycharmProjects/BENCHMARKforTST/semi-style-transfer/main.py", line 294, in <module>
    train_process(model, data_train)
  File "/home/usr/PycharmProjects/BENCHMARKforTST/semi-style-transfer/main.py", line 185, in train_process
    supervised_loss, cyclic_loss, GAN_dis_loss, GAN_gen_loss, transferred_sen_text, _ = model.batch_train(batch, train_epoch)
  File "/home/usr/PycharmProjects/BENCHMARKforTST/semi-style-transfer/Model.py", line 375, in batch_train
    supervised_loss, cyclic_loss, GAN_dis_loss, GAN_gen_loss, transferred_sen_text, binary_cls_res, style_average_lambda = self.forward(batch)
  File "/home/usr/PycharmProjects/BENCHMARKforTST/semi-style-transfer/Model.py", line 256, in forward
    = self.agent.rewrite_sentence_RL(batch_input_tensor, batch_attention_mask, greedy_generation=False, plus_sampling_generation=True)
  File "/home/usr/PycharmProjects/BENCHMARKforTST/semi-style-transfer/Model.py", line 77, in rewrite_sentence_RL
    min_length=set_min_length, max_length=set_max_length, use_cache=False)
ValueError: too many values to unpack (expected 2)
python-BaseException

Then I check the bug and the error is in that line(https://github.com/seq-to-mind/semi-style-transfer/blob/ebe7d69d65e48878949c452236fbf74703062afa/Model.py#L73-L75):

It seems that BartForConditionalGeneration.generate() only returns "output_sampling_sen_token_ids", but that line requires both "output_sampling_sen_token_ids" and "output_sampling_sen_token_logits".
And I have no idea how to fix it.

Your reply will be greatly appreciated.

**Comment by seq-to-mind** [comment]
We changed the `generation_utils.py` of the transformer library to support return the logits.
`generation_utils.py` is uploaded in the repo, you can download and put it to the transformer python library folder.
For instance: `___your_python_env_path___/lib/python3.8/site-packages/transformers/`

Moreover, if you want to change the original `generation_utils.py` directly, you can search all places with the comments "**updated for return logits after generation**" for detailed changes.

**Comment by FayeXXX** [comment]
Thank you sooooo much for that quik reply, and it works.! That is so great!

**Comment by seq-to-mind** [comment]
Ok, I closed this thread as it has been solved.
